### PR TITLE
Add contribute section at README

### PR DESCRIPTION
**Pull request by yanmagale**
By issue #73 and for better visualization, i add contribute section at README.md

### CODE REVIEW

**Comment by KingPixil** [comment]
Thanks for the contribution!

**Comment by KingPixil** [comment]
Just a tip: this commit won't show up on your profile, as it isn't linked to your account. If you did this locally, you can use the following to configure `git`.

```sh
git config user.name "Your Name"
git config user.email "your@email.com"
```

This will link your commits with your account from now on, but not any previous commits (such as the one above).

**Comment by yanmagale** [comment]
Yep, I ended up forgetting to set up my Github account on the office computer. Thanks for remenber :smile:

**Comment by KingPixil** [comment]
No problem!

**Pull request merged**
